// global.js
// generated by AI
window.addEventListener('pageshow', () => {
	document.body.classList.add('fade-in');
});

document.addEventListener('click', (event) => {
	if (
		event.defaultPrevented ||
		event.button !== 0 ||
		event.metaKey ||
		event.ctrlKey ||
		event.shiftKey ||
		event.altKey ||
		!(event.target instanceof Element)
	) {
		return;
	}

	const link = event.target.closest('a');
	if (!link || link.hasAttribute('download') || (link.target && link.target !== '_self')) {
		return;
	}

	const targetUrl = new URL(link.href, window.location.href);
	if (
		targetUrl.origin !== window.location.origin ||
		targetUrl.hash ||
		targetUrl.href === window.location.href
	) {
		return;
	}

	event.preventDefault();
	document.body.classList.remove('fade-in');

	window.setTimeout(() => {
		window.location.assign(targetUrl.href);
	}, 250);
});
